I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scenes/allestire_scacchiera_omote.rpy", line 251, in script
    ck "Ora sono molto più sicuro di me stesso. Ma ancora non ho chiaro al 100% quello che è accaduto, ne come funzioni la cospirazione davvero."
ValueError: unsupported format character 'q' (0x71) at index 72

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scenes/allestire_scacchiera_omote.rpy", line 251, in script
    ck "Ora sono molto più sicuro di me stesso. Ma ancora non ho chiaro al 100% quello che è accaduto, ne come funzioni la cospirazione davvero."
  File "C:\Users\david\OneDrive\Desktop\higu proCheckt\renpy-8.0.2-sdk\renpy\ast.py", line 921, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "C:\Users\david\OneDrive\Desktop\higu proCheckt\renpy-8.0.2-sdk\renpy\exports.py", line 1362, in say
    what = what % tag_quoting_dict
ValueError: unsupported format character 'q' (0x71) at index 72

Windows-10-10.0.19045 AMD64
Ren'Py 8.0.2.22081402
Higurashi: Gli indizi perduti - Meakashi 1.0
Tue Mar 26 00:23:58 2024
